//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMA.WebExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public System.DateTime DateMade { get; set; }
        public string CommentText { get; set; }
        public int CustomerId { get; set; }
        public int ReservationId { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
