//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMA.WebExample.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LocalDatabaseEntities : DbContext
    {
        public LocalDatabaseEntities()
            : base("name=LocalDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tour> Tour { get; set; }
        public virtual DbSet<Departure> Departure { get; set; }
        public virtual DbSet<Reservation> Reservation { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<RoomType> RoomType { get; set; }
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<RoomReservation> RoomResetvation { get; set; }
        public virtual DbSet<FlightReservation> FlightReservation { get; set; }
    }
}
