//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMA.WebExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departure()
        {
            this.FlightReservationTours = new HashSet<FlightReservation>();
        }
    
        public int DepartureId { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public int SeatsAvailableDeparture { get; set; }
        public int SeatsAvailableReturn { get; set; }
        public string DeparturePlace { get; set; }
        public string Destination { get; set; }
    
        public virtual Tour Tour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightReservation> FlightReservationTours { get; set; }
        public virtual FlightReservation FlightReservationRetours { get; set; }
    }
}
