//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMA.WebExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Comments = new HashSet<Comment>();
            this.Rooms = new HashSet<RoomReservation>();
        }
    
        public int ReservationId { get; set; }
        public string State { get; set; }
        public string HowMade { get; set; }
        public int RoomTypeId { get; set; }
        public int PayerId { get; set; }
        public int TravelerId { get; set; }
    
        public virtual FlightReservation FlightReservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Customer Payer { get; set; }
        public virtual Customer Traveler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomReservation> Rooms { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
