//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMA.WebExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomReservation
    {
        public int RoomResetvationId { get; set; }
        public string SpecialRequest { get; set; }
        public string IsExtraBedNeeded { get; set; }
        public int RoomTypeId { get; set; }
        public int ReservationId { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
